### ISSUE TITLE
nw-builder 4.5.3 requires WINE on Windows 11

### ISSUE THREAD

**Issue by DzikuVx** [nwutils/nw-builder#1002]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

NW-builder executed on Windows 11 fails when requesting WINE to update the exe icon

Execution:
```
nwbuild({
            srcDir: './dist/**/*',
            mode: "build",
            version: version,
            flavor: "normal",
            platform: "win",
            arch: "x64",
            outDir: appsDir,
            cache: true,
            zip: false,
            app: {
                name: pkg.description,
                version: pkg.version,
                icon: './images/inav.ico'
            }
        })
```

Error:
```
Renaming EXE failed or unable to modify EXE. If it's the latter, ensure WINE is installed or build your application Windows platform
ExitCodeError: Command failed with a non-zero return code (1):
C:\Users\Pawel\Projects\inav-configurator\node_modules\rcedit\bin\rcedit-x64.exe C:\Users\Pawel\Projects\inav-configurator\apps\INAV Configurator.exe --set-version-string FileDescription INAV Configurator --set-version-string FileVersion 7.0.1 --set-version-string InternalName INAV Configurator --set-version-string OriginalFilename INAV Configurator --set-version-string PrivateBuild INAV Configurator --set-version-string ProductName INAV Configurator --set-version-string ProductVersion 7.0.1 --set-version-string SpecialBuild INAV Configurator --set-file-version 7.0.1 --set-product-version 7.0.1 --set-icon ./images/inav.ico

Unable to load file: "C:\Users\Pawel\Projects\inav-configurator\apps\INAV Configurator.exe"
    at ChildProcess.<anonymous> (C:\Users\Pawel\Projects\inav-configurator\node_modules\@malept\cross-spawn-promise\dist\src\index.js:99:24)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:551:15)
    at cp.emit (C:\Users\Pawel\Projects\inav-configurator\node_modules\@malept\cross-spawn-promise\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:551:15)
    at Pipe.<anonymous> (node:net:337:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
```

### Expected/Proposed Behaviour

nw-builder does not require WINE to be present on Windows env.

### Additional Info

- Package version: 4.5.3
- Operating System: Windows 11
- Node version: 20.10.0
- NW.js version: 0.81.0
- Repro link: https://github.com/iNavFlight/inav-configurator/pull/1931
- ...

**Comment by ayushmanchhabra** [comment]
I'm not sure if this is an nw-builder issue or nwjs issue.

https://github.com/electron/node-rcedit/commit/8370d623654db2766e1ae7fb32e4cbb0cba5c3cc

https://github.com/nwjs/nw.js/issues/8152

**Comment by DzikuVx** [comment]
Thanks @ayushmanchhabra

**Comment by bmatusiak** [comment]
https://github.com/ZJONSSON/node-unzipper/issues/286

the zip extraction is corrupted in windows11 using nodejs v18.16.0 and above
