### ISSUE TITLE
Build windows versions in Mac OS X Catalina (10.15.4)

### ISSUE THREAD

**Issue by catacs** [nwutils/nw-builder#528]
After upgrading to Mac OS X 10.15.4 we noticed that wine 32 bits is not longer compatible with system. This module is dependent to winresourcer which executes 32 bits wine command.

When you try to execute wine in Mac OS X 10.15.4 you will get:

```
wine
bad CPU type in executable: wine
```

On the other hand the error dispatched by nw-builder is:

```

Unhandled rejection Error: spawn Unknown system error -86
    at _errnoException (util.js:1003:13)
    at ChildProcess.spawn (internal/child_process.js:340:11)
    at exports.spawn (child_process.js:499:9)
    at module.exports (/Users/user/projects/desktop/node_modules/winresourcer/lib/WinResourcer.js:70:14)
    at tryCatcher (/Users/user/projects/desktop/node_modules/bluebird/js/release/util.js:16:23)
    at ret (<anonymous>:15:23)
    at /Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/nw-builder/lib/index.js:658:13
    at Promise._execute (/Users/user/projects/desktop/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:79:10)
    at /Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/nw-builder/lib/index.js:654:22
    at /Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/nw-builder/lib/index.js:761:16
    at /Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/lodash/lodash.js:4938:15
    at baseForOwn (/Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/lodash/lodash.js:2988:24)
    at /Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/lodash/lodash.js:4907:18
    at Function.forEach (/Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/lodash/lodash.js:9319:14)
    at NwBuilder._forEachPlatform (/Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/nw-builder/lib/index.js:760:7)
    at NwBuilder.handleWinApp (/Users/user/projects/desktop/node_modules/grunt-nw-builder/node_modules/nw-builder/lib/index.js:650:10)
    at NwBuilder.tryCatcher (/Users/user/projects/desktop/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/user/projects/desktop/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/user/projects/desktop/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/user/projects/desktop/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/user/projects/desktop/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

For developers using mac to generate builds of an application for mac and windows this is an important issue because they no longer can use the nw-builder module to do it.

**Comment by MadLittleMods** [comment]
:+1: Running into the same thing on macOS 10.15.3

Here is a related issue for `electron-forge`, https://github.com/electron-userland/electron-forge/issues/1122#issuecomment-565099198 which suggeted installing the latest `wine` from homebrew to get `wine64` installed

**Comment by ayushmxn** [comment]
Let me know if this issue still happens.
