### ISSUE TITLE
Window10 build error: Path is a directory: cp returned EISDIR

### ISSUE THREAD

**Issue by qq253498229** [nwutils/nw-builder#819]
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Other

### Current/Missing Behaviour

```
F:\soft\Yarn\bin\yarn.cmd run build:win64
yarn run v1.22.19
$ node build/build.mjs --platform=win64
[ DEBUG ] 2023-03-19T13:48:26.488Z nwbuild property is not defined in package.json
[ DEBUG ] 2023-03-19T13:48:26.491Z Manifest file already exists locally under D:\src\game\angular\happy-cultivation\cache
[ DEBUG ] 2023-03-19T13:48:26.491Z Store manifest metadata in memory
[ DEBUG ] 2023-03-19T13:48:26.493Z Search for 0.73.0 specific release data
[ DEBUG ] 2023-03-19T13:48:26.494Z Using cached NW.js binaries
[ DEBUG ] 2023-03-19T13:48:26.494Z Remove any files at D:\src\game\angular\happy-cultivation\out\win64 directory
[ DEBUG ] 2023-03-19T13:48:26.495Z Copy D:\src\game\angular\happy-cultivation\cache\nwjs-v0.73.0-win-x64 files to D:\src\game\angular\happy-cultivation\out\win64 dire
ctory
[ DEBUG ] 2023-03-19T13:48:26.916Z Copy files in srcDir to D:\src\game\angular\happy-cultivation\out\win64 directory
[ DEBUG ] 2023-03-19T13:48:26.917Z Copy ./temp/3rdpartylicenses.txt file to D:\src\game\angular\happy-cultivation\out\win64 directory
[ DEBUG ] 2023-03-19T13:48:26.919Z Copy ./temp/assets file to D:\src\game\angular\happy-cultivation\out\win64 directory
[ ERROR ] 2023-03-19T13:48:26.921Z Path is a directory: cp returned EISDIR (\\?\D:\src\game\angular\happy-cultivation\temp\assets is a directory (not copied)) \\?\D:\
src\game\angular\happy-cultivation\temp\assets
[ ERROR ] 2023-03-19T13:48:26.921Z Path is a directory: cp returned EISDIR (\\?\D:\src\game\angular\happy-cultivation\temp\assets is a directory (not copied)) \\?\D:\
src\game\angular\happy-cultivation\temp\assets
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

SystemError [ERR_FS_EISDIR]: Path is a directory: cp returned EISDIR (\\?\D:\src\game\angular\happy-cultivation\temp\assets is a directory (not copied)) \\?\D:\src\ga
me\angular\happy-cultivation\temp\assets
    at new SystemError (node:internal/errors:238:5)
    at new NodeError (node:internal/errors:349:7)
    at getStatsForCopy (node:internal/fs/cp/cp:213:11)
    at async build (file:///D:/src/game/angular/happy-cultivation/node_modules/nw-builder/src/bld/build.js:42:5)
    at async nwbuild (file:///D:/src/game/angular/happy-cultivation/node_modules/nw-builder/src/nwbuild.js:212:7) {
  code: 'ERR_FS_EISDIR',
  info: {
    message: '\\\\?\\D:\\src\\game\\angular\\happy-cultivation\\temp\\assets is a directory (not copied)',
    path: '\\\\?\\D:\\src\\game\\angular\\happy-cultivation\\temp\\assets',
    syscall: 'cp',
    errno: 21,
    code: 'EISDIR'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter],
  path: [Getter/Setter],
  level: 'error',
  timestamp: '2023-03-19T13:48:26.921Z',
  [Symbol(level)]: 'error',
  [Symbol(message)]: '[ ERROR ] 2023-03-19T13:48:26.921Z Path is a directory: cp returned EISDIR (\\\\?\\D:\\src\\game\\angular\\happy-cultivation\\temp\\assets is a 
directory (not copied)) \\\\?\\D:\\src\\game\\angular\\happy-cultivation\\temp\\assets'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1

```

![image](https://user-images.githubusercontent.com/31200516/226180098-2eee9501-77fd-4e2a-a1eb-fb077b496b79.png)

### Expected/Proposed Behaviour

Normal build completed.

### Additional Info

- Package version: 4.1.1-beta.2
- Operating System: Window 10
- Node version: v16.17.1
- NW.js version: 8.15.0
- Repro link:
- ...

**Comment by qq253498229** [comment]
It seems that the error disappears, after check whether isDirectory before cp:

![image](https://user-images.githubusercontent.com/31200516/226182210-350da9f1-be52-4053-91f4-5ce0204b4e0d.png)

**Comment by tharatau** [comment]
That's great! Are there any directories/files missing after the code change?

**Comment by sysrage** [comment]
That code change isn't a fix, it only works if your entire app is inside the one directory. If any directory needs to be copied recursively, it would be skipped.

**Comment by tharatau** [comment]
This should work if glob is disabled. Tracking that in #836.
